<a href="https://colab.research.google.com/github/Soundk05/python_proj/blob/main/project111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/natality-1.4L.csv")

<ipython-input-3-40c84707e9d0>:1: DtypeWarning: Columns (5,12,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/natality-1.4L.csv")


In [4]:
df.head(5)

source_year  year  month  day  wday state  is_male  child_race  \
0         2005  2005      1  NaN   3.0   NaN     True         NaN   
1         2005  2005      2  NaN   7.0   NaN    False         NaN   
2         2005  2005      5  NaN   4.0   NaN    False         NaN   
3         2005  2005      8  NaN   4.0   NaN    False         NaN   
4         2005  2005      5  NaN   6.0   NaN     True         NaN   

   weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
0       7.804364        1.0  ...          NaN              NaN   
1       5.374870        2.0  ...        False              NaN   
2       6.437498        1.0  ...          NaN              NaN   
3       6.560957        1.0  ...          NaN              NaN   
4       8.811877        1.0  ...          NaN              NaN   

  weight_gain_pounds  born_alive_alive  born_alive_dead  born_dead ever_born  \
0               99.0               5.0              2.0        1.0       8.0   
1                8.0               9.0              0.0        0.0      10.0   
2               99.0               NaN              NaN        NaN       NaN   
3               25.0               NaN              NaN        NaN       NaN   
4               99.0               NaN              NaN        NaN       NaN   

  father_race father_age record_weight  
0        38.0         24             1  
1         1.0         31             1  
2         NaN         31             1  
3         NaN         99             1  
4         NaN         33             1  

[5 rows x 31 columns]

In [5]:
df1=df

In [6]:
df1.head(10)

source_year  year  month  day  wday state  is_male  child_race  \
0         2005  2005      1  NaN   3.0   NaN     True         NaN   
1         2005  2005      2  NaN   7.0   NaN    False         NaN   
2         2005  2005      5  NaN   4.0   NaN    False         NaN   
3         2005  2005      8  NaN   4.0   NaN    False         NaN   
4         2005  2005      5  NaN   6.0   NaN     True         NaN   
5         2005  2005      5  NaN   4.0   NaN    False         NaN   
6         2005  2005     10  NaN   6.0   NaN     True         NaN   
7         2005  2005     10  NaN   2.0   NaN     True         NaN   
8         2005  2005     10  NaN   2.0   NaN    False         NaN   
9         2005  2005      9  NaN   6.0   NaN    False         NaN   

   weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
0       7.804364        1.0  ...          NaN              NaN   
1       5.374870        2.0  ...        False              NaN   
2       6.437498        1.0  ...          NaN              NaN   
3       6.560957        1.0  ...          NaN              NaN   
4       8.811877        1.0  ...          NaN              NaN   
5       6.124442        1.0  ...          NaN              NaN   
6       6.876218        1.0  ...          NaN              NaN   
7       6.757168        1.0  ...          NaN              NaN   
8       8.688418        1.0  ...          NaN              NaN   
9       6.999677        1.0  ...          NaN              NaN   

  weight_gain_pounds  born_alive_alive  born_alive_dead  born_dead ever_born  \
0               99.0               5.0              2.0        1.0       8.0   
1                8.0               9.0              0.0        0.0      10.0   
2               99.0               NaN              NaN        NaN       NaN   
3               25.0               NaN              NaN        NaN       NaN   
4               99.0               NaN              NaN        NaN       NaN   
5               99.0               0.0              0.0        0.0       1.0   
6               25.0               0.0              0.0        1.0       1.0   
7               25.0               0.0              0.0        0.0       1.0   
8               47.0               0.0              0.0        0.0       1.0   
9               42.0               0.0              0.0        0.0       1.0   

  father_race father_age record_weight  
0        38.0         24             1  
1         1.0         31             1  
2         NaN         31             1  
3         NaN         99             1  
4         NaN         33             1  
5         7.0         33             1  
6         NaN         50             1  
7         NaN         24             1  
8         NaN         30             1  
9         NaN         30             1  

[10 rows x 31 columns]

In [56]:
df1.groupby("state").count()

source_year   year  month   day  wday  is_male  child_race  \
state                                                               
AK            2367   2367   2367  1121  1246     2367        2223   
AL           14258  14258  14258  7262  6996    14258       13438   
AR             271    271    271   271     0      271         271   

       weight_pounds  plurality  apgar_1min  ...  alcohol_use  \
state                                        ...                
AK              2359       2318        1965  ...         1243   
AL             14240      13790       11003  ...         6975   
AR               270          6           0  ...            0   

       drinks_per_week  weight_gain_pounds  born_alive_alive  born_alive_dead  \
state                                                                           
AK                  80                1236              2339             2327   
AL                 160                6885             14249            14250   
AR                   0                   0               270              271   

       born_dead  ever_born  father_race  father_age  record_weight  
state                                                                
AK          2319       2318         2367        2367           2367  
AL         14249      14247        14258       14258          14258  
AR           271        270          271         271            271  

[3 rows x 30 columns]

In [10]:
df1.source_year.nunique()

40

In [11]:
df1.source_year.unique()

array([2005, 2006, 2007, 2008, 1969, 1970, 1971, 1972, 1973, 1974, 1975,
       1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986,
       1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997,
       1998, 1999, 2000, 2001, 2002, 2003, 2004])

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 31 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   source_year             140000 non-null  int64  
 1   year                    140000 non-null  int64  
 2   month                   140000 non-null  int64  
 3   day                     8654 non-null    float64
 4   wday                    131346 non-null  float64
 5   state                   16896 non-null   object 
 6   is_male                 140000 non-null  bool   
 7   child_race              15932 non-null   float64
 8   weight_pounds           139862 non-null  float64
 9   plurality               139218 non-null  float64
 10  apgar_1min              12968 non-null   float64
 11  apgar_5min              128067 non-null  float64
 12  mother_residence_state  16896 non-null   object 
 13  mother_race             75675 non-null   float64
 14  mother_age          

In [13]:
df.isnull().sum()


source_year                    0
year                           0
month                          0
day                       131346
wday                        8654
state                     123104
is_male                        0
child_race                124068
weight_pounds                138
plurality                    782
apgar_1min                127032
apgar_5min                 11933
mother_residence_state    123104
mother_race                64325
mother_age                     0
gestation_weeks             2301
lmp                            0
mother_married                12
mother_birth_state        123747
cigarette_use              81576
cigarettes_per_day        134232
alcohol_use                74321
drinks_per_week           136403
weight_gain_pounds         11178
born_alive_alive           93590
born_alive_dead            93623
born_dead                  93652
ever_born                    723
father_race                64325
father_age                     0
record_weight                  0
dtype: int64

In [14]:
df1.describe()

source_year           year          month          day  \
count  140000.000000  140000.000000  140000.000000  8654.000000   
mean     2004.259136    2004.259136       6.551007    15.753062   
std         7.060152       7.060152       3.422586     8.770039   
min      1969.000000    1969.000000       1.000000     1.000000   
25%      2005.000000    2005.000000       4.000000     8.000000   
50%      2006.000000    2006.000000       7.000000    16.000000   
75%      2007.000000    2007.000000       9.000000    23.000000   
max      2008.000000    2008.000000      12.000000    31.000000   

                wday    child_race  weight_pounds      plurality  \
count  131346.000000  15932.000000  139862.000000  139218.000000   
mean        4.059926      3.647125       7.210949       1.034248   
std         1.830445      3.509630       1.321106       0.190698   
min         1.000000      1.000000       0.500449       1.000000   
25%         3.000000      1.000000       6.560957       1.000000   
50%         4.000000      2.000000       7.312733       1.000000   
75%         6.000000      9.000000       8.024826       1.000000   
max         7.000000      9.000000      16.459712       5.000000   

         apgar_1min     apgar_5min  ...  cigarettes_per_day  drinks_per_week  \
count  12968.000000  128067.000000  ...         5768.000000      3597.000000   
mean      37.750463       8.942116  ...           15.087205         3.274951   
std       42.633430       2.813285  ...           23.312643        17.424963   
min        1.000000       0.000000  ...            1.000000         0.000000   
25%        8.000000       9.000000  ...            5.000000         0.000000   
50%        9.000000       9.000000  ...           10.000000         0.000000   
75%       99.000000       9.000000  ...           10.250000         0.000000   
max       99.000000      99.000000  ...           99.000000        99.000000   

       weight_gain_pounds  born_alive_alive  born_alive_dead     born_dead  \
count       128822.000000      46410.000000     46377.000000  46348.000000   
mean            39.383785          1.054471         0.060073      0.360663   
std             25.401934          1.521494         1.633688      1.779838   
min              1.000000          0.000000         0.000000      0.000000   
25%             23.000000          0.000000         0.000000      0.000000   
50%             32.000000          1.000000         0.000000      0.000000   
75%             45.000000          2.000000         0.000000      0.000000   
max             99.000000         77.000000        77.000000     77.000000   

           ever_born   father_race     father_age  record_weight  
count  139277.000000  75675.000000  140000.000000  140000.000000  
mean        2.081399     15.978077      40.709250       1.014436  
std         1.255689     33.844786      25.403633       0.119279  
min         1.000000      1.000000      11.000000       1.000000  
25%         1.000000      1.000000      26.000000       1.000000  
50%         2.000000      1.000000      31.000000       1.000000  
75%         3.000000      2.000000      39.000000       1.000000  
max        15.000000     99.000000      99.000000       2.000000  

[8 rows x 23 columns]

In [15]:
df1.child_race.unique()

array([nan,  1.,  3.,  2.,  7.,  6.,  9.,  4.,  5.])

In [19]:
df1[df1[['child_race']].notnull().all(1)].tail(100)

source_year  year  month   day  wday state  is_male  child_race  \
139900         1970  1970      8  31.0   NaN    AR     True         2.0   
139901         1970  1970      5  12.0   NaN    AR    False         1.0   
139902         1970  1970      9  23.0   NaN    AR    False         2.0   
139903         1970  1970      6   5.0   NaN    AR     True         1.0   
139904         1970  1970      1  20.0   NaN    AR    False         1.0   
...             ...   ...    ...   ...   ...   ...      ...         ...   
139995         1971  1971     11  10.0   NaN    AR    False         1.0   
139996         1971  1971     12  20.0   NaN    AR    False         1.0   
139997         1971  1971      6  14.0   NaN    AR    False         1.0   
139998         1971  1971      5  18.0   NaN    AR     True         1.0   
139999         1971  1971      4  17.0   NaN    AR     True         1.0   

        weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
139900       5.813590        NaN  ...          NaN              NaN   
139901       7.187070        NaN  ...          NaN              NaN   
139902       6.124442        NaN  ...          NaN              NaN   
139903       8.999270        NaN  ...          NaN              NaN   
139904       7.312733        NaN  ...          NaN              NaN   
...               ...        ...  ...          ...              ...   
139995       6.375769        1.0  ...          NaN              NaN   
139996       7.251004        1.0  ...          NaN              NaN   
139997       6.624891        1.0  ...          NaN              NaN   
139998       6.437498        1.0  ...          NaN              NaN   
139999       6.937947        1.0  ...          NaN              NaN   

       weight_gain_pounds  born_alive_alive  born_alive_dead  born_dead  \
139900                NaN               0.0              0.0        0.0   
139901                NaN               0.0              0.0        0.0   
139902                NaN               0.0              0.0        0.0   
139903                NaN               0.0              0.0        0.0   
139904                NaN               1.0              0.0        0.0   
...                   ...               ...              ...        ...   
139995                NaN               0.0              0.0        0.0   
139996                NaN               0.0              0.0        0.0   
139997                NaN               0.0              0.0        0.0   
139998                NaN               0.0              0.0        0.0   
139999                NaN               NaN              0.0        0.0   

       ever_born father_race father_age record_weight  
139900       1.0         9.0         99             2  
139901       1.0         1.0         22             2  
139902       1.0         2.0         19             2  
139903       1.0         1.0         19             2  
139904       2.0         1.0         26             2  
...          ...         ...        ...           ...  
139995       1.0         1.0         21             2  
139996       1.0         1.0         22             2  
139997       1.0         1.0         26             2  
139998       1.0         1.0         20             2  
139999       NaN         1.0         29             2  

[100 rows x 31 columns]

In [20]:
df1[['wday', 'child_race']]

wday  child_race
0        3.0         NaN
1        7.0         NaN
2        4.0         NaN
3        4.0         NaN
4        6.0         NaN
...      ...         ...
139995   NaN         1.0
139996   NaN         1.0
139997   NaN         1.0
139998   NaN         1.0
139999   NaN         1.0

[140000 rows x 2 columns]

In [21]:
df1.head(5)

source_year  year  month  day  wday state  is_male  child_race  \
0         2005  2005      1  NaN   3.0   NaN     True         NaN   
1         2005  2005      2  NaN   7.0   NaN    False         NaN   
2         2005  2005      5  NaN   4.0   NaN    False         NaN   
3         2005  2005      8  NaN   4.0   NaN    False         NaN   
4         2005  2005      5  NaN   6.0   NaN     True         NaN   

   weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
0       7.804364        1.0  ...          NaN              NaN   
1       5.374870        2.0  ...        False              NaN   
2       6.437498        1.0  ...          NaN              NaN   
3       6.560957        1.0  ...          NaN              NaN   
4       8.811877        1.0  ...          NaN              NaN   

  weight_gain_pounds  born_alive_alive  born_alive_dead  born_dead ever_born  \
0               99.0               5.0              2.0        1.0       8.0   
1                8.0               9.0              0.0        0.0      10.0   
2               99.0               NaN              NaN        NaN       NaN   
3               25.0               NaN              NaN        NaN       NaN   
4               99.0               NaN              NaN        NaN       NaN   

  father_race father_age record_weight  
0        38.0         24             1  
1         1.0         31             1  
2         NaN         31             1  
3         NaN         99             1  
4         NaN         33             1  

[5 rows x 31 columns]

In [23]:
df1[df1.columns[7:15]]

child_race  weight_pounds  plurality  apgar_1min  apgar_5min  \
0              NaN       7.804364        1.0         NaN         NaN   
1              NaN       5.374870        2.0         NaN         8.0   
2              NaN       6.437498        1.0         NaN         7.0   
3              NaN       6.560957        1.0         NaN         9.0   
4              NaN       8.811877        1.0         NaN         9.0   
...            ...            ...        ...         ...         ...   
139995         1.0       6.375769        1.0         NaN         NaN   
139996         1.0       7.251004        1.0         NaN         NaN   
139997         1.0       6.624891        1.0         NaN         NaN   
139998         1.0       6.437498        1.0         NaN         NaN   
139999         1.0       6.937947        1.0         NaN         NaN   

       mother_residence_state  mother_race  mother_age  
0                         NaN         38.0          30  
1                         NaN          1.0          29  
2                         NaN          NaN          24  
3                         NaN          NaN          26  
4                         NaN          NaN          22  
...                       ...          ...         ...  
139995                     AR          1.0          19  
139996                     AR          1.0          19  
139997                     AR          1.0          20  
139998                     AR          1.0          18  
139999                     AR          1.0          19  

[140000 rows x 8 columns]

In [32]:
cnt=np.where(df1['weight_pounds']<=5)
cnt

(array([    30,     59,     80, ..., 139915, 139916, 139974]),)

In [33]:
#find the length of cnt
len(cnt[0])

6824

In [34]:
df1["mother_residence_state"].unique()

array([nan, 'AK', 'CA', 'FL', 'OH', 'NV', 'TX', 'AL', 'MS', 'AR', 'TN',
       'KS', 'GA', 'SC', 'MI', 'SD', 'MN', 'LA', 'ME', 'NC', 'IN', 'HI',
       'OK', 'MO'], dtype=object)

In [41]:
df1.groupby("mother_age").count()

source_year  year  month  day  wday  state  is_male  child_race  \
mother_age                                                                    
12                    7     7      7    2     5      3        7           3   
13                   46    46     46    5    41      9       46           9   
14                  240   240    240   50   190     76      240          72   
15                  704   704    704  110   594    170      704         164   
16                 1593  1593   1593  198  1395    348     1593         334   
17                 2822  2822   2822  344  2478    598     2822         576   
18                 4373  4373   4373  466  3907    841     4373         802   
19                 5895  5895   5895  527  5368    986     5895         946   
20                 6738  6738   6738  625  6113   1128     6738        1076   
21                 7041  7041   7041  631  6410   1130     7041        1077   
22                 7309  7309   7309  634  6675   1119     7309        1057   
23                 7566  7566   7566  580  6986   1054     7566         988   
24                 7756  7756   7756  612  7144   1055     7756         999   
25                 7707  7707   7707  544  7163   1027     7707         969   
26                 8013  8013   8013  526  7487   1012     8013         954   
27                 7856  7856   7856  468  7388    949     7856         897   
28                 7779  7779   7779  424  7355    881     7779         830   
29                 7485  7485   7485  386  7099    792     7485         756   
30                 7262  7262   7262  296  6966    680     7262         639   
31                 6611  6611   6611  270  6341    603     6611         561   
32                 6030  6030   6030  219  5811    513     6030         473   
33                 5528  5528   5528  179  5349    421     5528         390   
34                 4938  4938   4938  144  4794    352     4938         326   
35                 4327  4327   4327  102  4225    297     4327         271   
36                 3774  3774   3774   83  3691    220     3774         197   
37                 3008  3008   3008   76  2932    194     3008         178   
38                 2323  2323   2323   51  2272    147     2323         133   
39                 1715  1715   1715   28  1687     87     1715          77   
40                 1363  1363   1363   33  1330     95     1363          78   
41                  855   855    855   19   836     46      855          41   
42                  586   586    586    9   577     24      586          23   
43                  373   373    373    6   367     17      373          15   
44                  177   177    177    1   176      5      177           4   
45                   90    90     90    4    86      9       90           9   
46                   50    50     50    2    48      5       50           5   
47                   32    32     32    0    32      3       32           3   
48                    6     6      6    0     6      0        6           0   
49                    8     8      8    0     8      0        8           0   
50                   14    14     14    0    14      0       14           0   

            weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
mother_age                            ...                                 
12                      7          7  ...            3                0   
13                     46         45  ...           25                0   
14                    240        236  ...           99                3   
15                    702        698  ...          288               10   
16                   1590       1576  ...          702               31   
17                   2815       2785  ...         1256               82   
18                   4368       4322  ...         1965              148   
19                   5890       5830  ...         2670              229   
20                   6

In [43]:
a=df1["mother_age"].unique()

In [44]:
tuple(sorted(a))

(12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50)

In [45]:
df1["mother_race"].sort_values()

66819     1.0
84377     1.0
84380     1.0
84381     1.0
84385     1.0
         ... 
123098    NaN
123099    NaN
123101    NaN
123102    NaN
123103    NaN
Name: mother_race, Length: 140000, dtype: float64

In [47]:
df1["mother_race"].nunique()

15

In [48]:
df1["mother_race"].unique()

array([38.,  1., nan,  7.,  4., 78., 48., 18.,  2., 28.,  3., 68.,  5.,
        6., 58.,  9.])

In [51]:
df1["father_race"].unique()

array([38.,  1., nan,  7.,  4., 78., 68., 18., 48., 99., 28.,  2.,  5.,
        6.,  3., 58.,  9.])

In [52]:
df1["child_race"].unique()

array([nan,  1.,  3.,  2.,  7.,  6.,  9.,  4.,  5.])

In [54]:
a=df["year"]!=df["source_year"]
a.unique()


array([False])

In [58]:
df1["record_weight"].unique() # changed 'uniuqe' to 'unique'

array([1, 2])

In [59]:
df1.drop_duplicates()

source_year  year  month   day  wday state  is_male  child_race  \
0              2005  2005      1   NaN   3.0   NaN     True         NaN   
1              2005  2005      2   NaN   7.0   NaN    False         NaN   
2              2005  2005      5   NaN   4.0   NaN    False         NaN   
3              2005  2005      8   NaN   4.0   NaN    False         NaN   
4              2005  2005      5   NaN   6.0   NaN     True         NaN   
...             ...   ...    ...   ...   ...   ...      ...         ...   
139995         1971  1971     11  10.0   NaN    AR    False         1.0   
139996         1971  1971     12  20.0   NaN    AR    False         1.0   
139997         1971  1971      6  14.0   NaN    AR    False         1.0   
139998         1971  1971      5  18.0   NaN    AR     True         1.0   
139999         1971  1971      4  17.0   NaN    AR     True         1.0   

        weight_pounds  plurality  ...  alcohol_use  drinks_per_week  \
0            7.804364        1.0  ...          NaN              NaN   
1            5.374870        2.0  ...        False              NaN   
2            6.437498        1.0  ...          NaN              NaN   
3            6.560957        1.0  ...          NaN              NaN   
4            8.811877        1.0  ...          NaN              NaN   
...               ...        ...  ...          ...              ...   
139995       6.375769        1.0  ...          NaN              NaN   
139996       7.251004        1.0  ...          NaN              NaN   
139997       6.624891        1.0  ...          NaN              NaN   
139998       6.437498        1.0  ...          NaN              NaN   
139999       6.937947        1.0  ...          NaN              NaN   

       weight_gain_pounds  born_alive_alive  born_alive_dead  born_dead  \
0                    99.0               5.0              2.0        1.0   
1                     8.0               9.0              0.0        0.0   
2                    99.0               NaN              NaN        NaN   
3                    25.0               NaN              NaN        NaN   
4                    99.0               NaN              NaN        NaN   
...                   ...               ...              ...        ...   
139995                NaN               0.0              0.0        0.0   
139996                NaN               0.0              0.0        0.0   
139997                NaN               0.0              0.0        0.0   
139998                NaN               0.0              0.0        0.0   
139999                NaN               NaN              0.0        0.0   

       ever_born father_race father_age record_weight  
0            8.0        38.0         24             1  
1           10.0         1.0         31             1  
2            NaN         NaN         31             1  
3            NaN         NaN         99             1  
4            NaN         NaN         33             1  
...          ...         ...        ...           ...  
139995       1.0         1.0         21             2  
139996       1.0         1.0         22             2  
139997       1.0         1.0         26             2  
139998       1.0         1.0         20             2  
139999       NaN         1.0         29             2  

[140000 rows x 31 columns]

In [62]:
df1=df1.drop(['source_year','mother_residence_state',"mother_married","mother_birth_state","father_race"], axis=1)

In [61]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 31 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   source_year             140000 non-null  int64  
 1   year                    140000 non-null  int64  
 2   month                   140000 non-null  int64  
 3   day                     8654 non-null    float64
 4   wday                    131346 non-null  float64
 5   state                   16896 non-null   object 
 6   is_male                 140000 non-null  bool   
 7   child_race              15932 non-null   float64
 8   weight_pounds           139862 non-null  float64
 9   plurality               139218 non-null  float64
 10  apgar_1min              12968 non-null   float64
 11  apgar_5min              128067 non-null  float64
 12  mother_residence_state  16896 non-null   object 
 13  mother_race             75675 non-null   float64
 14  mother_age          

In [63]:
df1

year  month   day  wday state  is_male  child_race  weight_pounds  \
0       2005      1   NaN   3.0   NaN     True         NaN       7.804364   
1       2005      2   NaN   7.0   NaN    False         NaN       5.374870   
2       2005      5   NaN   4.0   NaN    False         NaN       6.437498   
3       2005      8   NaN   4.0   NaN    False         NaN       6.560957   
4       2005      5   NaN   6.0   NaN     True         NaN       8.811877   
...      ...    ...   ...   ...   ...      ...         ...            ...   
139995  1971     11  10.0   NaN    AR    False         1.0       6.375769   
139996  1971     12  20.0   NaN    AR    False         1.0       7.251004   
139997  1971      6  14.0   NaN    AR    False         1.0       6.624891   
139998  1971      5  18.0   NaN    AR     True         1.0       6.437498   
139999  1971      4  17.0   NaN    AR     True         1.0       6.937947   

        plurality  apgar_1min  ...  cigarettes_per_day  alcohol_use  \
0             1.0         NaN  ...                 NaN          NaN   
1             2.0         NaN  ...                 NaN        False   
2             1.0         NaN  ...                 NaN          NaN   
3             1.0         NaN  ...                 NaN          NaN   
4             1.0         NaN  ...                 NaN          NaN   
...           ...         ...  ...                 ...          ...   
139995        1.0         NaN  ...                 NaN          NaN   
139996        1.0         NaN  ...                 NaN          NaN   
139997        1.0         NaN  ...                 NaN          NaN   
139998        1.0         NaN  ...                 NaN          NaN   
139999        1.0         NaN  ...                 NaN          NaN   

        drinks_per_week  weight_gain_pounds born_alive_alive born_alive_dead  \
0                   NaN                99.0              5.0             2.0   
1                   NaN                 8.0              9.0             0.0   
2                   NaN                99.0              NaN             NaN   
3                   NaN                25.0              NaN             NaN   
4                   NaN                99.0              NaN             NaN   
...                 ...                 ...              ...             ...   
139995              NaN                 NaN              0.0             0.0   
139996              NaN                 NaN              0.0             0.0   
139997              NaN                 NaN              0.0             0.0   
139998              NaN                 NaN              0.0             0.0   
139999              NaN                 NaN              NaN             0.0   

        born_dead ever_born  father_age  record_weight  
0             1.0       8.0          24              1  
1             0.0      10.0          31              1  
2             NaN       NaN          31              1  
3             NaN       NaN          99              1  
4             NaN       NaN          33              1  
...           ...       ...         ...            ...  
139995        0.0       1.0          21              2  
139996        0.0       1.0          22              2  
139997        0.0       1.0          26              2  
139998        0.0       1.0          20              2  
139999        0.0       NaN          29              2  

[140000 rows x 26 columns]

In [64]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140000 entries, 0 to 139999
Data columns (total 26 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   year                140000 non-null  int64  
 1   month               140000 non-null  int64  
 2   day                 8654 non-null    float64
 3   wday                131346 non-null  float64
 4   state               16896 non-null   object 
 5   is_male             140000 non-null  bool   
 6   child_race          15932 non-null   float64
 7   weight_pounds       139862 non-null  float64
 8   plurality           139218 non-null  float64
 9   apgar_1min          12968 non-null   float64
 10  apgar_5min          128067 non-null  float64
 11  mother_race         75675 non-null   float64
 12  mother_age          140000 non-null  int64  
 13  gestation_weeks     137699 non-null  float64
 14  lmp                 140000 non-null  object 
 15  cigarette_use       58424 non-null

In [65]:
df1['lmp'] = pd.to_datetime(df1['lmp'])


DateParseError: month must be in 1..12: 11142007, at position 1667

In [67]:
!pip install pyspark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.3/317.3 MB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.2-py2.py3-none-any.whl size=317812365 sha256=28117b52f81c6059307bfaaa0e683072ad37a8caac8f9aa5f3c1afcad082272d
  Stored in directory: /root/.cache/pip/wheels/34/34/bd/03944534c44b677cd5859f248090daa9fb27b3c8f8e5f49574
Successfully built pyspark


In [68]:
from pyspark.sql  import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *

In [69]:
spark=SparkSession.builder.appName("Basics").getOrCreate()

In [73]:
df=spark.read.csv("/content/natality-1.4L.csv",header=True,inferSchema=True)

In [74]:
df.show()

+-----------+----+-----+----+----+-----+-------+----------+------------------+---------+----------+----------+----------------------+-----------+----------+---------------+--------+--------------+------------------+-------------+------------------+-----------+---------------+------------------+----------------+---------------+---------+---------+-----------+----------+-------------+
|source_year|year|month| day|wday|state|is_male|child_race|     weight_pounds|plurality|apgar_1min|apgar_5min|mother_residence_state|mother_race|mother_age|gestation_weeks|     lmp|mother_married|mother_birth_state|cigarette_use|cigarettes_per_day|alcohol_use|drinks_per_week|weight_gain_pounds|born_alive_alive|born_alive_dead|born_dead|ever_born|father_race|father_age|record_weight|
+-----------+----+-----+----+----+-----+-------+----------+------------------+---------+----------+----------+----------------------+-----------+----------+---------------+--------+--------------+------------------+-------------

In [75]:
df1=df

In [86]:
df1=df1.withColumn("lmp",to_date(col("lmp"),"MMddyyyy"))

AttributeError: 'NoneType' object has no attribute 'withColumn'

In [82]:
df1.where(df1.lmp.isNull()).count()


AttributeError: 'NoneType' object has no attribute 'where'

In [85]:
df1.filter(df1.lmp=="NULL").count().show()


AttributeError: 'NoneType' object has no attribute 'filter'